export const BID_STATUS = {
    PENDING_CONFIRM: 'PENDING_CONFIRM', // 승인 대기
    REJECT_CONFIRM: 'REJECT_CONFIRM', // 승인 거부
    COMPLETE_CONFIRM: 'COMPLETE_CONFIRM', // 승인 완료
    WAITING_BID: 'WAITING_BID', // 입찰 대기
    ONGOING_BID: 'ONGOING_BID', // 진행중
    COMPLETE_BID: 'COMPLETE_BID' // 입찰 완료
};
